version: 2
jobs:
  build:
    docker:
       - image: circleci/ruby:2.4.1-node-browsers
    steps:
      - checkout

      - type: cache-restore
        key: kanji-{{ checksum "Gemfile.lock" }}

      - run: bundle install --path vendor/bundle

      - run: bundle exec rspec

        #- run: bundle exec rubocop -R
